[project]
name = "newsfeed-backend"
version = "0.1.0"
description = "Newsfeed GraphQL Backend"
authors = [
    {name = "Dragoon788",email = "109482739+Dragoon788@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "django (>=5.2.1,<6.0.0)",
    "ariadne[django] (>=0.26.2,<0.27.0)",
    "django-cors-headers (>=4.7.0,<5.0.0)",
    "ariadne-django (>=0.3.0,<0.4.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
